# Generated by Django 3.1.1 on 2020-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante',
            field=models.CharField(blank=True, choices=[('BO', 'Boleta'), ('FA', 'Factura')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo_confirmacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TD', 'Tarjeta de débito'), ('TC', 'Tarjeta de crédito'), ('PA', 'Paypall')], max_length=2, null=True),
        ),
    ]
