# Generated by Django 3.1.1 on 2020-12-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201130_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TD', 'Tarjeta de débito'), ('TC', 'Tarjeta de crédito'), ('PA', 'Paypal')], max_length=2, null=True),
        ),
    ]
