# Generated by Django 3.1.1 on 2020-12-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201130_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('TA', 'Tarjeta de crédito/débito'), ('PA', 'Paypal')], max_length=2, null=True),
        ),
    ]
