# Generated by Django 3.1.1 on 2020-12-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201130_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='factura_razon_social',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='factura_ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
