# Generated by Django 3.1.3 on 2020-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201130_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_pago',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='factura_razon_social',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
