# Generated by Django 3.1.3 on 2020-12-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201130_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='correo_confirmacion',
        ),
    ]
